// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6WLpn3BD2zBfz1RNqP5hIBsF3jeM2hg',
    appId: '1:523886403992:web:4c54f154c4a24799e10bed',
    messagingSenderId: '523886403992',
    projectId: 'radioplayer-c9e00',
    authDomain: 'radioplayer-c9e00.firebaseapp.com',
    storageBucket: 'radioplayer-c9e00.appspot.com',
    measurementId: 'G-3F73DT2MEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtn0OMVA9fKNhkZFpkVOL-dGVUr9yRsME',
    appId: '1:523886403992:android:94eddd2a867a03dbe10bed',
    messagingSenderId: '523886403992',
    projectId: 'radioplayer-c9e00',
    storageBucket: 'radioplayer-c9e00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2n-nJi-wWzh1_OewQpVYHBv3dwCKP3nM',
    appId: '1:523886403992:ios:67c4a2b354e19b07e10bed',
    messagingSenderId: '523886403992',
    projectId: 'radioplayer-c9e00',
    storageBucket: 'radioplayer-c9e00.appspot.com',
    iosBundleId: 'ru.pawka.radio.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2n-nJi-wWzh1_OewQpVYHBv3dwCKP3nM',
    appId: '1:523886403992:ios:67c4a2b354e19b07e10bed',
    messagingSenderId: '523886403992',
    projectId: 'radioplayer-c9e00',
    storageBucket: 'radioplayer-c9e00.appspot.com',
    iosBundleId: 'ru.pawka.radio.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB6WLpn3BD2zBfz1RNqP5hIBsF3jeM2hg',
    appId: '1:523886403992:web:90b2d5f19a355a83e10bed',
    messagingSenderId: '523886403992',
    projectId: 'radioplayer-c9e00',
    authDomain: 'radioplayer-c9e00.firebaseapp.com',
    storageBucket: 'radioplayer-c9e00.appspot.com',
    measurementId: 'G-VYXS52P151',
  );

}